### ISSUE TITLE
bug:  `kcp bind compute` does not work as expected for locations on a different workspace

### ISSUE THREAD

**Issue by pdettori** [kcp-dev/kcp#2737]
### Describe the bug

I created a new workspace `inventory` under the home workspace (e.g. `kvdk2spgmbix`), and generate a syncer yaml from there and deploy the syncer on a pCluster.  At this point I check the path for the workspace where my location is:
```
$ kubectl ws .
Current workspace is "kvdk2spgmbix:inventory".
```
Then, I create a new workspace under the home workspace, for example `ws1` and enter there:
```
kubectl ws 
kubectl ws create ws1 --enter
```
Finally, I try to bind to the workspace containing the location:
```
kubectl kcp bind compute kvdk2spgmbix:inventory
```
But I get this error:

```
Binding APIExport "root:compute:kubernetes".
placement placement-1syj10fy created.
error: placement "placement-1syj10fy" not ready: placement is not scheduled: No selected location is scheduled
```
I found that in order to make this work, I have to use the cluster name, not the name in the form `kvdk2spgmbix:inventory`.
So I had to look up the cluster name in the yaml of the inventory workspace - e.g.
```
$ kubectl ws 
$ kubectl get workspace inventory -o yaml | grep " cluster:"
cluster: 36jjanpr01gl8d45
```
then I can bind with this cluster name and placement becomes healthy:

```
$ kubectl kcp bind compute 36jjanpr01gl8d45
Binding APIExport "root:compute:kubernetes".
placement placement-i152ylce created.
Placement "placement-i152ylce" is ready.
```

### Steps To Reproduce

1.  create fresh kind cluster
```
kind delete cluster --name control && kind create cluster --name control
```
2. fetch & merge latest main, run build
```
make build
export PATH=$(pwd)/bin:$PATH  
```
3. Build locally the syncer image
```
brew install ko
ko build --local --push=false -B ./cmd/syncer -t $(git rev-parse --short HEAD)
```
(add --platform linux/amd64,linux/arm64 if building on a MBP M1)
4. Load image on kind
```
kind load docker-image ko.local/syncer:$(git rev-parse --short HEAD) --name control
```
5. Cleanup previous kcp state (if any) &  start kcp
```
rm -rf .kcp
kcp start
```
6. Open another terminal, and enter:
```
export KUBECONFIG=$(pwd)/.kcp/admin.kubeconfig
kubectl ws 
kubectl ws create inventory --enter
kubectl kcp workload sync control --syncer-image ko.local/syncer:$(git rev-parse --short HEAD) -o ${HOME}/syncer-control.yaml
```
7. start the syncer
```
$ KUBECONFIG=</path/to/kind/kubeconfig> kubectl apply -f  ${HOME}/syncer-control.yaml
```
8. check the path for the workspace where my location is:
```
$ kubectl ws .
Current workspace is "kvdk2spgmbix:inventory".
```
9. create a new workspace under the home workspace, for example `ws1` and enter there:
```
kubectl ws 
kubectl ws create ws1 --enter
```
10.  bind to the workspace containing the location:
```
kubectl kcp bind compute kvdk2spgmbix:inventory
```
11. Verify error:
```
Binding APIExport "root:compute:kubernetes".
placement placement-1syj10fy created.
error: placement "placement-1syj10fy" not ready: placement is not scheduled: No selected location is scheduled
```

### Expected Behaviour

I would expect to be able to use the workspace path+name I can get when inside that workspace with `kubectl ws .` when running the `kcp bind compute` command instead of the cluster name (that requires me to look inside the yaml of a workspace).

**Comment by lionelvillard** [comment]
FYI, I managed to reproduce it.

**Comment by davidfestal** [comment]
@qiujian16 @sttts Any idea ?

**Comment by wangke19** [comment]
I also hit the same issue with main branch, referred to the steps from https://github.com/kcp-dev/kcp,

```
$ k kcp --version
kcp version v1.24.3+kcp-v0.10.0-683-gca871c150f440b

$ k get ws ws1 -oyaml
apiVersion: tenancy.kcp.io/v1alpha1
kind: Workspace
metadata:
  annotations:
    experimental.tenancy.kcp.io/owner: '{"username":"kcp-admin"}'
    internal.tenancy.kcp.io/cluster: 1c5c5cykgh93ho8v
    internal.tenancy.kcp.io/shard: 1pfxsevk
    kcp.io/cluster: kvdk2spgmbix
  creationTimestamp: "2023-02-03T11:24:32Z"
  finalizers:
  - core.kcp.io/logicalcluster
  generation: 2
  labels:
    tenancy.kcp.io/phase: Ready
  name: ws1
  resourceVersion: "835"
  uid: 195ca3ba-efec-47b4-8761-55e9241551db
spec:
  URL: https://192.168.3.101:6443/clusters/1c5c5cykgh93ho8v
  cluster: 1c5c5cykgh93ho8v
  type:
    name: universal
    path: root
...

$ kubectl kcp bind compute 1c5c5cykgh93ho8v
placement placement-2i0nt46r created.
error: placement "placement-2i0nt46r" not ready: placement is not scheduled: No selected location is scheduled

$ oc get placement placement-2i0nt46r -o yaml
apiVersion: scheduling.kcp.io/v1alpha1
kind: Placement
metadata:
  annotations:
    kcp.io/cluster: kvdk2spgmbix
  creationTimestamp: "2023-02-03T11:26:39Z"
  generation: 1
  name: placement-2i0nt46r
  resourceVersion: "860"
  uid: b8cfccfa-d21d-412b-aca8-d604407281f5
spec:
  locationResource:
    group: workload.kcp.io
    resource: synctargets
    version: v1alpha1
  locationSelectors:
  - {}
  locationWorkspace: 1c5c5cykgh93ho8v
  namespaceSelector: {}
status:
  conditions:
  - lastTransitionTime: "2023-02-03T11:26:39Z"
    message: No valid location is found
    reason: LocationNoMatch
    severity: Error
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-02-03T11:26:39Z"
    message: No selected location is scheduled
    reason: ScheduleLocationNotFound
    severity: Warning
    status: "False"
    type: Scheduled
  phase: Pending
```

**Comment by qiujian16** [comment]
need to confirm with this issue. When we run bind, I think we can use either cluster name 36jjanpr01gl8d45 or a logical cluster name e.g. root:inventory, I do not think we can use a mixed path. Is this the case?

**Comment by pdettori** [comment]
I don't think we need "mixed". From a UX perspective logical cluster name (e.g. root:inventory)  it is way simpler to use, and it is what users normally interact with when for example creating a new workspace. There are additional steps required for a user to find what the cluster name is.

**Comment by qiujian16** [comment]
I see, thanks. I think the root cause is still that location update (when synctarget is added into the location) does not trigger the placement, which should be fixed with linked PR.

**Comment by pdettori** [comment]
@qiujian16 I have tested with the latest that includes the fix and I still see the issue. I have followed the steps in "Steps To Reproduce" and I still get the same issue:

```
git log
commit 90f961b33b4416d5f2a85e21e882a1bf47103b5e (HEAD -> main, upstream/main)
Merge: 9640af10 f9ce14dd
Author: OpenShift Merge Robot <openshift-merge-robot@users.noreply.github.com>
Date:   Tue Feb 21 16:50:09 2023 +0100
```
then I run `make build` and follow steps in "Steps To Reproduce" . Then I verify I am running the correct build:
```
kubectl version
....
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3+kcp-v0.11.0-alpha.1-85-g90f961b33b4416", GitCommit:"90f961b3", GitTreeState:"clean", BuildDate:"2023-02-21T16:21:55Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/arm64"}
```
I still get:
```
$ kubectl kcp bind compute kvdk2spgmbix:inventory
Binding APIExport "root:compute:kubernetes".
placement placement-1syj10fy created.
error: placement "placement-1syj10fy" not ready: placement is not scheduled: No selected location is scheduled
```

**Comment by pdettori** [comment]
After a discussion on Slack we found the root issue is that `kubectl ws .` displays the current workspace when working with workspaces created starting from the `home` workspace. This is currently being addressed by #2830

**Comment by pdettori** [comment]
I tested #2830 and verified that it resolves this issue.
