### ISSUE TITLE
checksum of pre built binaries didn't match at v0.24.0

### ISSUE THREAD

**Issue by suzuki-shunsuke** [kcp-dev/kcp#3121]
https://github.com/kcp-dev/kcp/releases/tag/v0.24.0

Download all assets with GitHub CLI. https://cli.github.com/manual/gh_release_download

```sh
gh -R kcp-dev/kcp release download v0.24.0
```

Checksum verification with sha256sum fails.

```console
$ sha256sum -c kcp_0.24.0_checksums.txt                                                            
kcp_0.24.0_darwin_amd64.tar.gz: OK
kcp_0.24.0_darwin_arm64.tar.gz: OK
kcp_0.24.0_linux_amd64.tar.gz: FAILED
kcp_0.24.0_linux_arm64.tar.gz: OK
kcp_0.24.0_linux_ppc64le.tar.gz: OK
kubectl-kcp-plugin_0.24.0_darwin_amd64.tar.gz: OK
kubectl-kcp-plugin_0.24.0_darwin_arm64.tar.gz: OK
kubectl-kcp-plugin_0.24.0_linux_amd64.tar.gz: FAILED
kubectl-kcp-plugin_0.24.0_linux_arm64.tar.gz: OK
kubectl-kcp-plugin_0.24.0_linux_ppc64le.tar.gz: OK
kubectl-kcp-plugin_0.24.0_windows_amd64.tar.gz: OK
kubectl-kcp-plugin_0.24.0_windows_arm64.tar.gz: OK
kubectl-kcp-ws-plugin_0.24.0_darwin_amd64.tar.gz: OK
kubectl-kcp-ws-plugin_0.24.0_darwin_arm64.tar.gz: OK
kubectl-kcp-ws-plugin_0.24.0_linux_amd64.tar.gz: FAILED
kubectl-kcp-ws-plugin_0.24.0_linux_arm64.tar.gz: FAILED
kubectl-kcp-ws-plugin_0.24.0_linux_ppc64le.tar.gz: OK
kubectl-kcp-ws-plugin_0.24.0_windows_amd64.tar.gz: OK
kubectl-kcp-ws-plugin_0.24.0_windows_arm64.tar.gz: OK
sha256sum: WARNING: 4 computed checksums did NOT match
```

```console
$ sha256sum -c kcp_0.24.0_checksums.txt | grep FAILED
kcp_0.24.0_linux_amd64.tar.gz: FAILED
kubectl-kcp-plugin_0.24.0_linux_amd64.tar.gz: FAILED
kubectl-kcp-ws-plugin_0.24.0_linux_amd64.tar.gz: FAILED
kubectl-kcp-ws-plugin_0.24.0_linux_arm64.tar.gz: FAILED
sha256sum: WARNING: 4 computed checksums did NOT match
```

kcp_0.24.0_checksums.txt

```
404322fa594d4eb981d27acbef6ada646a3819b8f3235a0276fa7e2c4686a5cc  kcp_0.24.0_darwin_amd64.tar.gz
a38ad48a7ddbc0e4125c4a6fbadb887a6e7cbf7265190694932975a8ff338c50  kcp_0.24.0_darwin_arm64.tar.gz
070e0669921622d0ec5aa72fcb6853c769372843662565ef2457e679f5623ac4  kcp_0.24.0_linux_amd64.tar.gz
cb560428345d7ecbe49c07cf5c1ca1c058a6f6b42daa32490391304cc98dc1da  kcp_0.24.0_linux_arm64.tar.gz
0dca0bcf425953710efb3fb2db0498294ebed16627f9b6dd18de83a61fe90f96  kcp_0.24.0_linux_ppc64le.tar.gz
209844ba26f0a8afe22eee44978561a24d1346a63bf41a4d72f6518ff1ce5750  kubectl-kcp-plugin_0.24.0_darwin_amd64.tar.gz
3b2816762645bab865f5e0d5c8877df2eb310b9ef3617f13f14348c79a03df4e  kubectl-kcp-plugin_0.24.0_darwin_arm64.tar.gz
3acd473895e1f843ac2c1818ab98f318b0cf79671e32007ea6523a525686fa48  kubectl-kcp-plugin_0.24.0_linux_amd64.tar.gz
a2297f858be2a582aa10adab8b82afd769076d8b17fec126cca2d62e75510a94  kubectl-kcp-plugin_0.24.0_linux_arm64.tar.gz
551d2282bee88c0697d867e52379658130e0ea6e58a71ed631a1d8950b5978a8  kubectl-kcp-plugin_0.24.0_linux_ppc64le.tar.gz
185a3f4be86cab3691d11c9911a119878230265841a36d7a3c34428d1561b2ac  kubectl-kcp-plugin_0.24.0_windows_amd64.tar.gz
c0b7d9d2059a6d585b8f99680d5e43fb0f03063b511c99c0acc4f412513aa0c1  kubectl-kcp-plugin_0.24.0_windows_arm64.tar.gz
b3f8c96c6da7a9af85599625bd8110ecea1132f980a91ebd7c21f44a6ff979d0  kubectl-kcp-ws-plugin_0.24.0_darwin_amd64.tar.gz
ba9b5f74639173bd7f03a00659a95daed2a1c79e6992e1787c125fa651575c6b  kubectl-kcp-ws-plugin_0.24.0_darwin_arm64.tar.gz
f6391f13c5522647018d9eef52d391c611c635406d217fb17704a3bd9aa9f5f2  kubectl-kcp-ws-plugin_0.24.0_linux_amd64.tar.gz
fe17ca01683a97bfeac41436448643bb8b18be9f49a08cd71715791bd36364eb  kubectl-kcp-ws-plugin_0.24.0_linux_arm64.tar.gz
851178bca09af9ed733903b89a7a1808bc1cbcc24e758974d1847cb29efc8562  kubectl-kcp-ws-plugin_0.24.0_linux_ppc64le.tar.gz
77cacc84215c0c535af48841d0c61859ede60b4fc4c1b89b618da4c33478a6ac  kubectl-kcp-ws-plugin_0.24.0_windows_amd64.tar.gz
97c2d56b4a8fc851dba7b833c9d13da6432ddd91e61a2b40a05c3285dce38ede  kubectl-kcp-ws-plugin_0.24.0_windows_arm64.tar.gz
```

```console
$ sha256sum kcp_0.24.0_linux_amd64.tar.gz kubectl-kcp-plugin_0.24.0_linux_amd64.tar.gz kubectl-kcp-ws-plugin_0.24.0_linux_amd64.tar.gz kubectl-kcp-ws-plugin_0.24.0_linux_arm64.tar.gz
6a3125956301d12ae31cd742cb6a3c36993d4557fa82a819d7c817a1f1379dc1  kcp_0.24.0_linux_amd64.tar.gz
3ec0716b0290b156af86abe641ecc459c5a6234f809fad6572cda7ce6992f8d8  kubectl-kcp-plugin_0.24.0_linux_amd64.tar.gz
adabad4c6171eba29521ce72e0c3e6a18476cd9362ce29daea50f7e044a4cf07  kubectl-kcp-ws-plugin_0.24.0_linux_amd64.tar.gz
396324005284a3ccbac4373a65f3ec4f60b113fd2e4b7cc89f2866a9880e28ce  kubectl-kcp-ws-plugin_0.24.0_linux_arm64.tar.gz
```

**Comment by embik** [comment]
Hey, thanks for reporting. We'll look into that!

**Comment by embik** [comment]
It looks like our goreleaser job ran three times at the same time for v0.24.0 because we set three tags: https://github.com/kcp-dev/kcp/actions/workflows/goreleaser.yml, racing to upload artefacts. We will fix that configuration for the next release, I'm following up on #3106.

**Comment by mjudeikis** [comment]
I think this is fixed now?

**Comment by embik** [comment]
I suppose it's not really fixed for 0.24, but I don't think we can re-run goreleaser to fix it. It's going to be fixed for the next release though.

**Comment by embik** [comment]
/remove-lifecycle stale

I'll keep this open until we have v0.25.0 released, so a release with correct checksums is available.

**Comment by embik** [comment]
Closing, since [v0.25.0](https://github.com/kcp-dev/kcp/releases/tag/v0.25.0) assets are looking fine and therefore there is a version with fixed checksums available.

```sh
$ sha256sum -c kcp_0.25.0_checksums.txt | grep -v OK | wc -l
0
```

/close
